{% set version = "1.0.15" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-doparallel
  version: {{ version|replace("-", "_") }}

source:
  fn: doParallel_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/doParallel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/doParallel/doParallel_{{ version }}.tar.gz
  sha256: 71ad7ea69616468996aefdd8d02a4a234759a21ddde9ed1657e3c537145cd86e

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0
  run:
    - r-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0

test:
  commands:
    - $R -e "library('doParallel')"           # [not win]
    - "\"%R%\" -e \"library('doParallel')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=doParallel
  license: GPL-2
  summary: Provides a parallel backend for the %dopar% function using the parallel package.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
