appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: r00Y+eEVHhfkJBdymsootVH2jhN6MN8r760QhHuOGSeTVMNALSyj0QyWks0qsRiT5yp53VNfRbO9p2Ud1Cdy8HElyOrcXG42P0yY7H3krwj3tNAoy4Mtofp6HfMac+BtOK4t2GDXMCw0wYMXWNc/P7WEQoNdHazptXtkxcFaH/Ub9haR0syeEsQ7NiFhZX35Gewyh1bofCht/oyudtAaPwACThZwG4LX3Prql4Sk6hrcIeYwnytt+8vhGRD1ZSw35iOdiOxWOUkaPOC6lvBgCoxS7SkpEuWiM8jDY2g81gQlNmDOF9MPIn9vTV8wpk+tEYSgpB4VYLlvxCmI1z1n0WxZc6Hr+hBPfLxzKaaGNTm0X1WinfMfdPPuJqDP3VOL3mhQasK4/AsE2FlJ2SNfcG7yhCTWwMOzVK+NqFzPrL+RtDqy0HHOl9GT/iwcC5/4aulCMMGc93vynp1i4SaQ4Qb2oJob/7sxaywWHTPDxTMl78ZqDBzIEvHYFJ2IFdeJyh4IKvkt6BaanNh8BwxLuem/uc281+mR7LyrJcgP92aJhqiOkEShdhyw0xTsnwQRqDnwg12CmuSN7khWgKtgu5x5pWRxH5FrTh86nRURMQYLon4GEydQREnMWa9WgK8OUMjZ2977+zrzLMu1IrH2ooQ3hkR7WDB2R00LFlcEuB4=}
bot:
  automerge: true
